name: Build and Push Docker Image

# Kịch bản này chạy khi nào? -> Khi có code push lên nhánh main
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # GitHub sẽ cấp cho bạn 1 con server Ubuntu ảo để chạy job này
    
    steps:
    # Bước 1: Lấy code từ kho về server ảo
    - name: Checkout code
      uses: actions/checkout@v3

    # Bước 2: Đăng nhập Docker Hub (Dùng chìa khóa bạn vừa cất trong Secret)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # Bước 3: Build ảnh và Đẩy lên Hub
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/monitor-web:latest
